### ISSUE TITLE
Register a key multiple times on the same environment with different scopes

### ISSUE THREAD

**Issue by dnnsthnnr** [mwiatrzyk/pydio#10]
Hi there,

I would propose to enhance the library to support the use case of registering a key twice with different scopes. 
Our specific use case would be to be able to inject the same storage class with a read/write or read-only database connection depending on the scope of the injector used.

Example adjusted from the docs:
```
provider = Provider()

@provider.provides('database_connenction', scope='app')
def make_database():
    ....

@provider.provides('database_connenction_ro', scope='app') 
def make_database_ro():
    ....


@provider.provides(ITodoItemStorage, scope='action')
def make_sqlite_todo_storage(injector):
    connection = injector.inject('database_connenction')  # (2)
    try:
        yield SQLiteTodoStorage(connection)  # (3)
    except Exception:
        connection.close()
    else:
        connection.commit()
 
@provider.provides(ITodoItemStorage, scope='action_ro')
def make_sqlite_todo_storage_ro(injector):
    connection = injector.inject('database_connenction_ro')  # (2)
    try:
        yield SQLiteTodoStorage(connection)  # (3)
    except Exception:
        connection.close()
```

Do you think this is feasible and a good enhancement?

**Comment by mwiatrzyk** [comment]
Hi,

This is not what the scopes are meant to be used for. Scopes are just used to limit lifetime of injected objects (so f.e. cleanup actions can be executed when API call is done, not when entire server is shut down).

Instead, I suggest to split interfaces into smaller ones by following interface segregation principle. With smaller interfaces you will end up with distinct provider keys, and you will be able to inject implementation depending on interface type, like so far.

For example, you can change from this:

```
class IDatabaseConnection(abc.ABC):
   ...
```

to this:

```
class IDatabaseConnectionReadOnly(abc.ABC):
   ...

class IDatabaseConnection(IDatabaseConnectionReadOnly):
   ...
```

And now you should be able to do different things based on interface type:

```
@provider.provides(IDatabaseConnection, scope='app')
def make_database():
    ....

@provider.provides(IDatabaseConnectionReadOnly, scope='app') 
def make_database_ro():
    ....
```

This is how I do this in my projects.

Alternatively, you could also try variants:
https://pydio.readthedocs.io/en/stable/api/keys.html#pydio.keys.Variant

And if my answer does not satisfy your needs, we can continue discussing your proposal here. I'm open for new ideas and will be thankful for any contributions to this tool.

BR,
Maciej

**Comment by dnnsthnnr** [comment]
Thanks for the answer! 
I see your point that my proposal contradicts the purpose of the scopes to limit the lifetime of an object.

I did not want to go for the variant injection keys as this would mean that within the same scope of an injector, we would introduce a pitfall of opening up two database connections if not being mindful.
E.g.
```
async with injector.scoped("action") as scoped_injector:
      storage_items = scoped_injector.inject(ITodoItemStorageRO) # creates a RO connection
      storage_actions = scoped_injector.inject(IActionStorage)  # created a second non RO connection. Not good!
```

I also thought about introducing a new environment flag while adding a scope but this is also not permitted. I think I will go the route of separate injection keys with variants bundled in a child injector so that everybody specifically either requests a RO db connection or a non-restricted connection.

**Comment by mwiatrzyk** [comment]
Do you need RO connection just for your business logic, or is it necessary to use some flags when connection with DB server is created?

It is still possible to use single RW connection, and simply wrap it with a RO proxy inside injector to make it "read only". Something like this:

```python
@provider.provides(IDbConnection, scope='app')
def make_connection():
    ...

@provider.provides(IDbConnectionRO, scope='app')
def make_read_only_connection(injector):
    rw = injector.inject(IDbConnection)
    return DbConnectionReadOnlyProxy(rw)
```

You still physically have one connection, but the user can pick from either RW or RO.

However, if you need specific flags on connection itself to make it RO, then I think you would need two separate connections anyway. But still, if you wrap it with right interfaces, you will end up with a code that automatically creates either RO, RW or both - depending on actual use case being executed.

And also it may be possible to separate network connection between app and DB server from sessions working on top of that connection. Then you'll end up with single connection, and different types of sessions, depending on what you want to achieve. But I'm not quite sure if that's doable, it's been a while since the last time I was working with DB servers :-)

BR,
Maciej

**Comment by mwiatrzyk** [comment]
Just one more thing that came to my mind...

I've once had a problem of delivering command line global params to injectors when using Click to create CLI app, and came out with following solution:

In providers I've declared something similar to this:

```python
@provider.provides('params')
def make_params():
    return {}  # empty dict

@provider.provides(ISomeCommand, scope='action')
def make_command(injector):
    params = injector.inject('params')
    return SomeCommand(**params)
```

And command execution looked like this:

```python
@click.group()
@click.option('--dry-run', ...)
def app(**kw):
    params = injector.inject('params')
    params.update(kw)

@app.command()
@click.option('--some-command-option', ...)
def some_command(**kw):
    return injector.inject(ISomeCommand).invoke(**kw)
```

I needed this to control dependency injectors depending on global flags like `--dry-run`, so I could detect (inside injector) that the command was run with that option, and based on that change the implementation of interface being injected. In other words, from the use case PoV it was completely transparent, but I could still modify the behavior of injectors without affecting business logic of the app.

Maybe this is what you are looking for? :-)

**Comment by dnnsthnnr** [comment]
Thanks for that example and the help, this is also a good option! I will tinker with this a bit.

I think it is safe to say that this issue can be closed 👍
